services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    hostname: server
    stop_signal: SIGINT
    ports:
      - "4000:4000"
  broker:
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
    build:
      context: ./broker
      dockerfile: Dockerfile
    stop_signal: SIGINT
    volumes:
      - ./broker:/broker