{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "method_latency_count", "legendFormat": "{{node}} {{method}}" }
   ]
  },
  {
   "title": "Server response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(method_latency_sum{node=\"server\"}[$__rate_interval]) ",
     "legendFormat": "{{method}}_{{node}}"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes) - sum(node_filesystem_avail_bytes)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(node_filesystem_size_bytes) ",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Brokers response time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(method_latency_sum[$__rate_interval])",
     "legendFormat": "{{method}}{{node}}"
    }
   ]
  }
 ]
}