name: Deploy

on:
  push:
    branches: [ production ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          ls
          cd /home/sad/SAD-Project-14/
          git pull origin production
          git status
          docker compose up -d --build
