name: Deploy

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          ls
          cd /home/sad/SAD-Project-14/
          git pull origin main
          git status
          docker build . --file ./broker/Dockerfile --tag my-image-name:$(date +%s) 
          docker compose up -d